### ISSUE TITLE
Glarab

### ISSUE THREAD

**Issue by moe1999** [alouche/rodent#15]
any news of GLarab.

**Comment by alouche** [comment]
Not sure what you mean with "GLarab". Can you please clarify?

**Comment by moe1999** [comment]
The GL Arab on shahid Arabic. The servers

**Comment by alouche** [comment]
Is it possible you are confusing this repo with an XMBC repo?

**Comment by moe1999** [comment]
Do you know what I am talking about

**Comment by alouche** [comment]
Sorry but I think you are confusing this repo with something else.
